### PR TITLE
[wip] github actions: add an action to run tests in an automated fashion

### PR DESCRIPTION
**Pull request by frisson**
### Description

Add a github action `test.yml` that builds the dev docker image and runs the test suite. 

### Notes

The tests depend on a number of secrets which are handled by github.

### CODE REVIEW

**Comment by frisson** [comment]
@dcalacci 
Looks like our action failed. It seems the credentials aren't are the problem. I think the way we're dumping the file may be affecting things. 

Can we make sure the google credentials secret is a single line of JSON as if it'd been passed to `jq -c`. 

I've added a step to the test job that validates the credentials are in a useable json format. It may provide some hints.

**Comment by frisson** [comment]
@dcalacci 

looks like the `GOOGLE_SERVICE_ACCOUNT_CREDENTIALS_JSON` are not being parsed as good json. Can we make sure that secret is in a single string? We may even need to base64 encode it just to be safe. 

GOOGLE_SERVICE_ACCOUNT_CREDENTIALS_JSON_B64=`cat service_account.json | jq -c | base64`

**Comment by frisson** [comment]
### RE: Long Builds

It looks like `pystan` is the culprit. There are no wheels for it on 3.8 or 3.9. If the base image doesn't get a tag, it'll use `latest` which uses python 3.9. Pinning the image to a version that use 3.7 helps a great deal.

**Comment by dcalacci** [comment]
@frisson Added the new secret! Good idea. b64 from jq, like you suggested. Let's see how the new pinned image works!

**Comment by dcalacci** [comment]
Files are getting pulled from storage correctly, but there's some issue with the parsing. Not sure exactly what yet.

**Comment by dcalacci** [comment]
Works now. I suspect we may have an issue downline with versioning on the opencv docker image but we will deal with that later

**Pull request merged**
